# Generated by Django 6.0.2 on 2026-02-15 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.PositiveIntegerField(default=0)),
                ('glucose', models.FloatField(default=85.0)),
                ('blood_pressure', models.FloatField(default=70.0)),
                ('skin_thickness', models.FloatField(default=20.0)),
                ('insulin', models.FloatField(default=0.0)),
                ('bmi', models.FloatField(default=25.0)),
                ('diabetes_pedigree_function', models.FloatField(default=0.5)),
                ('age', models.PositiveIntegerField(default=35)),
                ('probability', models.FloatField()),
                ('risk_level', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تحليل',
                'verbose_name_plural': 'التحاليل',
                'ordering': ['-created_at'],
            },
        ),
    ]
